// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc7Gx9BF5rCAMm-eXlDYZ055W_wSypqaw',
    appId: '1:273079324502:web:7ba351261b440125cb50f7',
    messagingSenderId: '273079324502',
    projectId: 'stylish-app-18604',
    authDomain: 'stylish-app-18604.firebaseapp.com',
    storageBucket: 'stylish-app-18604.appspot.com',
    measurementId: 'G-HDB7G2BBB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GoUWQi8gKbiFHRQT2kct3WODGwCkjQU',
    appId: '1:273079324502:android:c8491042137872a1cb50f7',
    messagingSenderId: '273079324502',
    projectId: 'stylish-app-18604',
    storageBucket: 'stylish-app-18604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa18cwwzBCO6OhecjKmeSq22TRvz7kKss',
    appId: '1:273079324502:ios:9cb87aaf407c1574cb50f7',
    messagingSenderId: '273079324502',
    projectId: 'stylish-app-18604',
    storageBucket: 'stylish-app-18604.appspot.com',
    androidClientId: '273079324502-sdh6ctr822n284tk8trqc2v0okh205vk.apps.googleusercontent.com',
    iosClientId: '273079324502-j6scpsi2rq1mbkg1teriukvuimn2is3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa18cwwzBCO6OhecjKmeSq22TRvz7kKss',
    appId: '1:273079324502:ios:3f86113efc75c20ccb50f7',
    messagingSenderId: '273079324502',
    projectId: 'stylish-app-18604',
    storageBucket: 'stylish-app-18604.appspot.com',
    androidClientId: '273079324502-sdh6ctr822n284tk8trqc2v0okh205vk.apps.googleusercontent.com',
    iosClientId: '273079324502-5kveo380lg05g7v67dis8j7ji42889u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylish.RunnerTests',
  );
}
