// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTpbkRwgSAputWPv51kFBMa9-kd1EfQbA',
    appId: '1:939129675686:web:3d4853426861ded3b07967',
    messagingSenderId: '939129675686',
    projectId: 'stylish-temp',
    authDomain: 'stylish-temp.firebaseapp.com',
    storageBucket: 'stylish-temp.appspot.com',
    measurementId: 'G-0ZVHQV0K83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ7Emay75h_9AU0snh_2XuhSHr5Rl66g8',
    appId: '1:939129675686:android:338335e6aff00cd0b07967',
    messagingSenderId: '939129675686',
    projectId: 'stylish-temp',
    storageBucket: 'stylish-temp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhmB-MPP6PepAfox-NKPG2YF-sB7hBz4',
    appId: '1:939129675686:ios:73cd52b68084a572b07967',
    messagingSenderId: '939129675686',
    projectId: 'stylish-temp',
    storageBucket: 'stylish-temp.appspot.com',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhmB-MPP6PepAfox-NKPG2YF-sB7hBz4',
    appId: '1:939129675686:ios:73cd52b68084a572b07967',
    messagingSenderId: '939129675686',
    projectId: 'stylish-temp',
    storageBucket: 'stylish-temp.appspot.com',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTpbkRwgSAputWPv51kFBMa9-kd1EfQbA',
    appId: '1:939129675686:web:04ed4dd8931f26dfb07967',
    messagingSenderId: '939129675686',
    projectId: 'stylish-temp',
    authDomain: 'stylish-temp.firebaseapp.com',
    storageBucket: 'stylish-temp.appspot.com',
    measurementId: 'G-03EY40QB69',
  );
}
